# Generated by Django 4.2.3 on 2023-08-17 00:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('miaplicacion', '0004_comprador'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido_compra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_pedido', models.DateTimeField(auto_now_add=True)),
                ('comprador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='miaplicacion.comprador')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='miaplicacion.producto')),
            ],
        ),
    ]
